version: '3'

networks:
    projet:

services:
    # nginx
    nginx-service:
        image: nginx:stable
        container_name: nginx-service
        tty: true
        ports:
            - "8082:80"
            - "443:443"
        volumes:
            - ./www:/var/www/project
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-service
            - mysql-service
        networks:
            - projet

    # php
    php-service:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php-service
        ports:
            - "9000:9000"
        volumes:
            - ./www:/var/www/project
        networks:
            - projet

    # mysql
    mysql-service:
        image: mysql:8
        container_name: mysql-service
        ports:
            - "3306:3306"
        volumes:
            - ./docker/datasource/mysql:/var/lib/mysql
            - ./projetbd.sql:/docker-entrypoint-initdb.d/projetbd.sql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: groupXX
        networks:
            - projet

    # php-my-admin
    phpmyadmin-service:
        image: phpmyadmin
        container_name: phpmyadmin-service
        restart: always
        ports:
            - "8083:80"
        environment:
            - PMA_HOST=mysql-service
            - PMA_PORT=3306
        depends_on:
            - mysql-service
        networks:
            - projet